
version: "3"

services:
  nodeosd:
    image: johnnyzhao/eosio-dawn-v4.1.0
    command: /usr/local/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "9876"
      - "8888"
    volumes:
      - /data/bios-node/:/opt/eosio/bin/data-dir

  nodeosd0:
    image: johnnyzhao/eosio-dawn-v4.1.0
    command: /usr/local/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir
    hostname: nodeosd
    ports:
      - 9875:9875
    expose:
      - "9875"
    volumes:
      - /data/eos-bp0/:/opt/eosio/bin/data-dir
  nodeosd1:
    image: johnnyzhao/eosio-dawn-v4.1.0
    command: /usr/local/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir
    hostname: nodeosd
    ports:
      - 9874:9874
    expose:
      - "9874"
    volumes:
      - /data/eos-bp1/:/opt/eosio/bin/data-dir
  nodeosd2:
    image: johnnyzhao/eosio-dawn-v4.1.0
    command: /usr/local/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir
    hostname: nodeosd
    ports:
      - 9873:9873
    expose:
      - "9873"
    volumes:
      - /data/eos-bp2/:/opt/eosio/bin/data-dir
  nodeosd3:
    image: johnnyzhao/eosio-dawn-v4.1.0
    command: /usr/local/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir
    hostname: nodeosd
    ports:
      - 9872:9872
    expose:
      - "9872"
    volumes:
      - /data/eos-bp3/:/opt/eosio/bin/data-dir
  nodeosd4:
    image: johnnyzhao/eosio-dawn-v4.1.0
    command: /usr/local/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir
    hostname: nodeosd
    ports:
      - 9871:9871
    expose:
      - "9871"
    volumes:
      - /data/eos-bp4/:/opt/eosio/bin/data-dir
